allowBuilds:
  "@swc/core": true
  core-js: true
  esbuild: true
  lefthook: true
  protobufjs: false
  workerd: true

minimumReleaseAge: 10080

minimumReleaseAgeExclude:
  - ras-stack-config@1.0.0
  - ras-stack@3.0.0
